spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: "jdbc:h2:mem:governance"
    driverClassName: org.h2.Driver
    username: 5gzorro_admin
    password: 5gzorro

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    eu._5gzorro.governancemanager.httpClient: DEBUG

callbacks:
  updateProposalIdentity: ${UPDATE_PROPOSAL_CALLBACK_URL:http://localhost:8080/api/v1/governance-actions/%s/identity}

deferredExecutionQueue:
  delay: ${DEFERRED_EXECUTION_QUEUE_DELAY:5000}