spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${postgres.db.host:localhost}:${postgres.db.port:5432}/${postgres.db.name:governance}
    driverClassName: org.postgresql.Driver
    username: ${postgres.db.user:5gzorro_admin}
    password: ${postgres.db.password:5gzorro}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

integrations:
  identity-permissions:
    apiBaseUrl: ${IDENTITY_BASE_URL:http://localhost:6200}

callbacks:
  updateProposalIdentity: ${UPDATE_PROPOSAL_CALLBACK_URL:http://localhost:8080/api/v1/governance-actions/%s/identity}