spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5432}/${POSTGRES_DB_NAME:governance}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_DB_USER:5gzorro_admin}
    password: ${POSTGRES_DB_PASSWORD:5gzorro}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

integrations:
  identity-permissions:
    myAgentBaseUrl: ${IDENTITY_BASE_URL:http://localhost:6200/}

callbacks:
  updateProposalIdentity: ${UPDATE_PROPOSAL_CALLBACK_URL:http://localhost:8080/api/v1/governance-actions/%s/identity}

deferredExecutionQueue:
  delay: ${DEFERRED_EXECUTION_QUEUE_DELAY:5000}

server:
  forward-headers-strategy: framework