spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5433/governance"
    driverClassName: org.postgresql.Driver
    username: 5gzorro_admin
    password: 5gzorro
    initialization-mode: never
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui