spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5433/governance"
    driverClassName: org.postgresql.Driver
    username: 5gzorro_admin
    password: 5gzorro
    initialization-mode: never

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

integrations:
  identity-permissions:
    apiBaseUrl: ${IDENTITY_BASE_URL:http://localhost:6200}

callbacks:
  updateProposalIdentity: ${UPDATE_PROPOSAL_CALLBACK_URL:http://localhost:8080/api/v1/governance-actions/%s/identity}